# XDEBUG_MODE from Compose overrides this setting. Keep Xdebug disabled by default.
xdebug.mode=off
xdebug.idekey=docker
xdebug.start_with_request=trigger
xdebug.log=/dev/stdout
xdebug.log_level=0
xdebug.client_port=9003
xdebug.client_host=host.docker.internal
