<?php
/*
 *   $Id$
 *
 *   AbanteCart, Ideal OpenSource Ecommerce Solution
 *   http://www.AbanteCart.com
 *
 *   Copyright © 2011-2024 Belavier Commerce LLC
 *
 *   This source file is subject to Open Software License (OSL 3.0)
 *   License details is bundled with this package in the file LICENSE.txt.
 *   It is also available at this URL:
 *   <http://www.opensource.org/licenses/OSL-3.0>
 *
 *  UPGRADE NOTE:
 *    Do not edit or add to this file if you wish to upgrade AbanteCart to newer
 *    versions in the future. If you wish to customize AbanteCart for your
 *    needs please refer to http://www.AbanteCart.com for more information.
 */

/** @var AController $this */
//prior upgrades fix
$sqlSelect = "SELECT * 
              FROM " . $this->db->table('dataset_definition') . "
              WHERE dataset_id=1 
                AND dataset_column_name = 'settings'";
$result = $this->db->query($sqlSelect);

if (!$result->num_rows) {
    $sqlAlter = "INSERT INTO " . $this->db->table('dataset_definition') . "
        (dataset_id, dataset_column_name, dataset_column_type,dataset_column_sort_order)
    VALUES (1,'settings','text',8)";
    $this->db->query($sqlAlter, true);
}
//upgrade icon with class fa-money to fa-money-bill inside RL !!!!!
// update menu item icon rl_id if template is novator/default and current icon contains fa-money class

/** @var ModelToolFormsManager $mdl */
$mdl = $this->load->model('tool/forms_manager');
$forms = [
    [
        'form_name'        => 'AddressFrm',
        'controller'       => '',
        'success_page'     => '',
        'status'           => 1,
        'locked'           => 1,
        'form_description' => 'Customer Address Form',
        'fields'           => [
            [
                'field_name'        => 'country_id',
                'element_type'      => 'O',
                'sort_order'        => 1,
                'attributes'        => '',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^[1-9]\d*$/',
                'resource_id'       => $fieldResources['country_id'],
                'locked'            => 0,
                'field_description' => 'Country',
                'field_note'        => '',
                'error_text'        => 'Please select a country!',
            ],
            [
                'field_name'        => 'zone_id',
                'element_type'      => 'Z',
                'sort_order'        => 2,
                'attributes'        => '',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^[1-9]\d*$/',
                'resource_id'       => $fieldResources['zone_id'],
                'locked'            => 0,
                'field_description' => 'Zone',
                'field_note'        => '',
                'error_text'        => 'Please select a region/state!',
            ],
            [
                'field_name'        => 'company',
                'element_type'      => 'I',
                'sort_order'        => 3,
                'attributes'        => '',
                'settings'          => '',
                'required'          => '0',
                'status'            => 1,
                'regexp_pattern'    => '/^.{0,32}$/u',
                'resource_id'       => $fieldResources['company'],
                'locked'            => 0,
                'field_description' => 'Company',
                'field_note'        => '',
                'error_text'        => 'Company Name must be less than 32 characters!',
            ],
            [
                'field_name'        => 'address_1',
                'element_type'      => 'I',
                'sort_order'        => 4,
                'attributes'        => 'minlength="3" maxlength="128"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^.{3,128}$/u',
                'resource_id'       => $fieldResources['address_1'],
                'locked'            => 0,
                'field_description' => 'Address Line 1',
                'field_note'        => '',
                'error_text'        => 'Address Line 1 must be between 3 and 128 characters!',
            ],
            [
                'field_name'        => 'address_2',
                'element_type'      => 'I',
                'sort_order'        => 5,
                'attributes'        => 'minlength="0" maxlength="128"',
                'settings'          => '',
                'required'          => '0',
                'status'            => 1,
                'regexp_pattern'    => '/^.{0,128}$/u',
                'resource_id'       => $fieldResources['address_2'],
                'locked'            => 0,
                'field_description' => 'Address Line 2',
                'field_note'        => '',
                'error_text'        => 'Address Line 2 must be less than 128 characters!',
            ],
            [
                'field_name'        => 'city',
                'element_type'      => 'I',
                'sort_order'        => 6,
                'attributes'        => 'maxlength="128"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^.{1,128}$/u',
                'resource_id'       => 100271,
                'locked'            => 0,
                'field_description' => 'City',
                'field_note'        => '',
                'error_text'        => 'City must be between 3 and 128 characters!',
            ],
            [
                'field_name'        => 'postcode',
                'element_type'      => 'I',
                'sort_order'        => 7,
                'attributes'        => '',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^[A-Za-z0-9\- ]+$/',
                'resource_id'       => 100266,
                'locked'            => 0,
                'field_description' => 'Zip/Post Code',
                'field_note'        => '',
                'error_text'        => 'Zip/Post Code must be less than 11 characters!',
            ],
            [
                'field_name'        => 'firstname',
                'element_type'      => 'I',
                'sort_order'        => 8,
                'attributes'        => 'minlength="1" maxlength="32"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^.{1,32}$/u',
                'resource_id'       => 100272,
                'locked'            => 0,
                'field_description' => 'First Name',
                'field_note'        => '',
                'error_text'        => 'First Name must be between 1 and 32 characters!',
            ],
            [
                'field_name'        => 'lastname',
                'element_type'      => 'I',
                'sort_order'        => 9,
                'attributes'        => 'minlength="1" maxlength="32"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^.{1,32}$/u',
                'resource_id'       => 100273,
                'locked'            => 0,
                'field_description' => 'Last Name',
                'field_note'        => '',
                'error_text'        => 'Last Name must be between 1 and 32 characters!',
            ],
            [
                'field_name'        => 'default',
                'element_type'      => 'C',
                'sort_order'        => 11,
                'attributes'        => '',
                'settings'          => '',
                'required'          => '0',
                'status'            => 1,
                'regexp_pattern'    => '',
                'resource_id'       => 0,
                'locked'            => 0,
                'field_description' => 'Default Address',
                'field_note'        => 'Vat Id',
                'error_text'        => '',
            ],
            [
                'field_name'        => 'vat_id',
                'element_type'      => 'I',
                'sort_order'        => 10,
                'attributes'        => '',
                'settings'          => '',
                'required'          => '0',
                'status'            => 1,
                'regexp_pattern'    => '/^.{8,14}$/u',
                'resource_id'       => 0,
                'locked'            => 0,
                'field_description' => 'VAT ID',
                'field_note'        => '',
                'error_text'        => 'VAT ID Code must be between 8 and 14 characters!',
            ],
        ],
    ],
    [
        'form_name'        => 'GuestCheckoutFrm',
        'controller'       => '',
        'success_page'     => '',
        'status'           => 1,
        'locked'           => 1,
        'form_description' => 'guest address and details form',
        'fields'           => [
            [
                'field_name'        => 'country_id',
                'element_type'      => 'O',
                'sort_order'        => 1,
                'attributes'        => 'data-pair-with="zone_id"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^[1-9]\d*$/',
                'resource_id'       => $fieldResources['country_id'],
                'locked'            => 1,
                'field_description' => 'Country',
                'field_note'        => '',
                'error_text'        => 'Please select a country!',
            ],
            [
                'field_name'        => 'zone_id',
                'element_type'      => 'Z',
                'sort_order'        => 2,
                'attributes'        => 'data-pair-with="country_id"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^[1-9]\d*$/',
                'resource_id'       => $fieldResources['zone_id'],
                'locked'            => 1,
                'field_description' => 'Region/State',
                'field_note'        => '',
                'error_text'        => 'Please select a region/state!',
            ],
            [
                'field_name'        => 'company',
                'element_type'      => 'I',
                'sort_order'        => 3,
                'attributes'        => '',
                'settings'          => '',
                'required'          => '0',
                'status'            => 1,
                'regexp_pattern'    => '/^.{0,32}$/u',
                'resource_id'       => $fieldResources['company'],
                'locked'            => 0,
                'field_description' => 'Company',
                'field_note'        => '',
                'error_text'        => 'Company Name must be less than 32 characters!',
            ],
            [
                'field_name'        => 'address_1',
                'element_type'      => 'I',
                'sort_order'        => 4,
                'attributes'        => 'minlength="3" maxlength="128"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^.{3,128}$/u',
                'resource_id'       => $fieldResources['address_1'],
                'locked'            => 1,
                'field_description' => 'Address Line 1',
                'field_note'        => '',
                'error_text'        => 'Address Line 1 must be between 3 and 128 characters!',
            ],
            [
                'field_name'        => 'address_2',
                'element_type'      => 'I',
                'sort_order'        => 5,
                'attributes'        => 'minlength="0" maxlength="128"',
                'settings'          => '',
                'required'          => '0',
                'status'            => 1,
                'regexp_pattern'    => '/^.{0,128}$/u',
                'resource_id'       => $fieldResources['address_2'],
                'locked'            => 0,
                'field_description' => 'Address Line 2',
                'field_note'        => '',
                'error_text'        => 'Address Line 2 must be less than 128 characters!',
            ],
            [
                'field_name'        => 'city',
                'element_type'      => 'I',
                'sort_order'        => 6,
                'attributes'        => 'maxlength="128" data-pair-with="postcode"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^.{1,128}$/u',
                'resource_id'       => $fieldResources,
                'locked'            => 1,
                'field_description' => 'City',
                'field_note'        => '',
                'error_text'        => 'City must be between 3 and 128 characters!',
            ],
            [
                'field_name'        => 'postcode',
                'element_type'      => 'I',
                'sort_order'        => 7,
                'attributes'        => 'data-pair-with="city"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^[A-Za-z0-9\- ]+$/',
                'resource_id'       => $fieldResources['address_1'],
                'locked'            => 1,
                'field_description' => 'Zip/Post Code',
                'field_note'        => '',
                'error_text'        => 'Zip/Post Code must be less than 11 characters!',
            ],
            [
                'field_name'        => 'firstname',
                'element_type'      => 'I',
                'sort_order'        => 8,
                'attributes'        => 'minlength="1" maxlength="32" data-pair-with="lastname"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^.{1,32}$/u',
                'resource_id'       => 100272,
                'locked'            => 1,
                'field_description' => 'First Name',
                'field_note'        => '',
                'error_text'        => 'First Name must be between 1 and 32 characters!',
            ],
            [
                'field_name'        => 'lastname',
                'element_type'      => 'I',
                'sort_order'        => 9,
                'attributes'        => 'minlength="1" maxlength="32" data-pair-with="firstname"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '/^.{1,32}$/u',
                'resource_id'       => 100273,
                'locked'            => 1,
                'field_description' => 'Last Name',
                'field_note'        => '',
                'error_text'        => 'Last Name must be between 1 and 32 characters!',
            ],
            [
                'field_name'        => 'vat_id',
                'element_type'      => 'I',
                'sort_order'        => 10,
                'attributes'        => '',
                'settings'          => '',
                'required'          => '0',
                'status'            => 1,
                'regexp_pattern'    => '/^.{8,14}$/u',
                'resource_id'       => 0,
                'locked'            => 0,
                'field_description' => 'VAT ID',
                'field_note'        => '',
                'error_text'        => 'VAT ID Code must be between 8 and 14 characters!',
            ],
            [
                'field_name'        => 'email',
                'element_type'      => 'E',
                'sort_order'        => 15,
                'attributes'        => 'minlength="1" maxlength="96"',
                'settings'          => '',
                'required'          => '1',
                'status'            => 1,
                'regexp_pattern'    => '',
                'resource_id'       => 100274,
                'locked'            => 1,
                'field_description' => 'Email',
                'field_note'        => '',
                'error_text'        => 'Your email is not provided or invalid!',
            ],
            [
                'field_name'        => 'telephone',
                'element_type'      => 'F',
                'sort_order'        => 16,
                'attributes'        => 'maxlength="32"',
                'settings'          => '',
                'required'          => '0',
                'status'            => 1,
                'regexp_pattern'    => '/^[0-9\+\(\)\.\s\-,]+$/',
                'resource_id'       => 100275,
                'locked'            => 0,
                'field_description' => 'Phone Number',
                'field_note'        => '',
                'error_text'        => 'Your contact phone number is not provided or invalid.',
            ],
        ],
    ]
];

foreach ($forms as $formData) {
    $formId = $mdl->addForm($formData);
    foreach ($formData['fields'] as $fieldData) {
        $fieldId = $mdl->addField($formId, $fieldData);
    }
}