<?php
/**
 * PackagePackageServiceOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\QuantumView
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Quantum View
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\QuantumView;

use PHPUnit\Framework\TestCase;

/**
 * PackagePackageServiceOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Defines service options used for the package(s).
 * @package     UPS\QuantumView
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PackagePackageServiceOptionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PackagePackageServiceOptions"
     */
    public function testPackagePackageServiceOptions()
    {
    }

    /**
     * Test attribute "cod"
     */
    public function testPropertyCod()
    {
    }

    /**
     * Test attribute "insured_value"
     */
    public function testPropertyInsuredValue()
    {
    }

    /**
     * Test attribute "earliest_delivery_time"
     */
    public function testPropertyEarliestDeliveryTime()
    {
    }

    /**
     * Test attribute "hazardous_materials_code"
     */
    public function testPropertyHazardousMaterialsCode()
    {
    }

    /**
     * Test attribute "hold_for_pickup"
     */
    public function testPropertyHoldForPickup()
    {
    }

    /**
     * Test attribute "add_shipping_charges_to_cod_indicator"
     */
    public function testPropertyAddShippingChargesToCodIndicator()
    {
    }
}
