<?php
/**
 * LabelRecoveryRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\Shipping
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ship
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\Shipping;

use PHPUnit\Framework\TestCase;

/**
 * LabelRecoveryRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request for obtaining the Label for the return shipment.
 * @package     UPS\Shipping
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LabelRecoveryRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LabelRecoveryRequest"
     */
    public function testLabelRecoveryRequest()
    {
    }

    /**
     * Test attribute "request"
     */
    public function testPropertyRequest()
    {
    }

    /**
     * Test attribute "label_specification"
     */
    public function testPropertyLabelSpecification()
    {
    }

    /**
     * Test attribute "translate"
     */
    public function testPropertyTranslate()
    {
    }

    /**
     * Test attribute "label_delivery"
     */
    public function testPropertyLabelDelivery()
    {
    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {
    }

    /**
     * Test attribute "mail_innovations_tracking_number"
     */
    public function testPropertyMailInnovationsTrackingNumber()
    {
    }

    /**
     * Test attribute "reference_values"
     */
    public function testPropertyReferenceValues()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "ups_premium_care_form"
     */
    public function testPropertyUpsPremiumCareForm()
    {
    }
}
