<?php
/**
 * AcceptanceAuditPreCheckRequestShipmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\DangerousGoods
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dangerous Goods Utility
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\DangerousGoods;

use PHPUnit\Framework\TestCase;

/**
 * AcceptanceAuditPreCheckRequestShipmentTest Class Doc Comment
 *
 * @category    Class
 * @description Contains shipment information.
 * @package     UPS\DangerousGoods
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AcceptanceAuditPreCheckRequestShipmentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AcceptanceAuditPreCheckRequestShipment"
     */
    public function testAcceptanceAuditPreCheckRequestShipment()
    {
    }

    /**
     * Test attribute "shipper_number"
     */
    public function testPropertyShipperNumber()
    {
    }

    /**
     * Test attribute "ship_from_address"
     */
    public function testPropertyShipFromAddress()
    {
    }

    /**
     * Test attribute "ship_to_address"
     */
    public function testPropertyShipToAddress()
    {
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
    }

    /**
     * Test attribute "regulation_set"
     */
    public function testPropertyRegulationSet()
    {
    }

    /**
     * Test attribute "package"
     */
    public function testPropertyPackage()
    {
    }
}
