<?php
/**
 * PickupGetServiceCenterFacilitiesRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\Pickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Pickup
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\Pickup;

use PHPUnit\Framework\TestCase;

/**
 * PickupGetServiceCenterFacilitiesRequestTest Class Doc Comment
 *
 * @category    Class
 * @description This request is to retrieve UPS Facility location information including location address, phone number, SLIC, and hours of operation for pick-up and drop-off requests
 * @package     UPS\Pickup
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PickupGetServiceCenterFacilitiesRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PickupGetServiceCenterFacilitiesRequest"
     */
    public function testPickupGetServiceCenterFacilitiesRequest()
    {
    }

    /**
     * Test attribute "request"
     */
    public function testPropertyRequest()
    {
    }

    /**
     * Test attribute "pickup_piece"
     */
    public function testPropertyPickupPiece()
    {
    }

    /**
     * Test attribute "origin_address"
     */
    public function testPropertyOriginAddress()
    {
    }

    /**
     * Test attribute "destination_address"
     */
    public function testPropertyDestinationAddress()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "proximity_search_indicator"
     */
    public function testPropertyProximitySearchIndicator()
    {
    }
}
