<?php
/**
 * ResponseShipmentItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\LandedCost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Landed Cost Quote API
 *
 * The Landed Cost Quote API allows you to estimate the all-inclusive cost of international shipments - including applicable duties, VAT, taxes, brokerage fees, and other fees. Required parameters include the currency and shipment details, such as the commodity ID, price, quantity, and country code of origin.  Key Business Values: - **Enhanced Customer Experience**: Get a quick and accurate quote on the landed cost of a shipment, including the cost of goods, transportation, and any other fees associated with getting the goods to their destination. - **Operational Efficiency**: Simplify the process of calculating landed costs by eliminating the need to manually research and calculate all of the different fees involved. - **Data-Driven Decision Making**: Improve decision-making by having a clear understanding of the total cost of shipping goods before you commit to a purchase.. - **Optimizing Cash Flow**: Streamline your shipping process by integrating the Landed Cost Quote API into your existing systems.
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\LandedCost;

use PHPUnit\Framework\TestCase;

/**
 * ResponseShipmentItemsTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseShipmentItems
 * @package     UPS\LandedCost
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseShipmentItemsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ResponseShipmentItems"
     */
    public function testResponseShipmentItems()
    {
    }

    /**
     * Test attribute "commodity_id"
     */
    public function testPropertyCommodityId()
    {
    }

    /**
     * Test attribute "hs_code"
     */
    public function testPropertyHsCode()
    {
    }

    /**
     * Test attribute "commodity_duty"
     */
    public function testPropertyCommodityDuty()
    {
    }

    /**
     * Test attribute "total_commodity_tax_and_fee"
     */
    public function testPropertyTotalCommodityTaxAndFee()
    {
    }

    /**
     * Test attribute "commodity_vat"
     */
    public function testPropertyCommodityVat()
    {
    }

    /**
     * Test attribute "total_commodity_duty_and_tax"
     */
    public function testPropertyTotalCommodityDutyAndTax()
    {
    }

    /**
     * Test attribute "commodity_currency_code"
     */
    public function testPropertyCommodityCurrencyCode()
    {
    }

    /**
     * Test attribute "is_calculable"
     */
    public function testPropertyIsCalculable()
    {
    }
}
