<?php
/**
 * UploadRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\Paperless
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperless Document
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\Paperless;

use PHPUnit\Framework\TestCase;

/**
 * UploadRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Paperless Document API Request container for uploading User Created Forms.
 * @package     UPS\Paperless
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UploadRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UploadRequest"
     */
    public function testUploadRequest()
    {
    }

    /**
     * Test attribute "request"
     */
    public function testPropertyRequest()
    {
    }

    /**
     * Test attribute "shipper_number"
     */
    public function testPropertyShipperNumber()
    {
    }

    /**
     * Test attribute "user_created_form"
     */
    public function testPropertyUserCreatedForm()
    {
    }
}
