name: Integration tests

on:
  push:
  pull_request:

jobs:
  integration:
    permissions:
      contents: read
    name: Integration tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4']
        db:
          - ver: mysql
            release: '8.0.40'  # Oldest supported
          - ver: mysql
            release: '8.4.3'  # Latest stable (or '9.0' if compatible)
          - ver: mariadb
            release: '10.11'  # Latest LTS
          - ver: mariadb
            release: '11.6'   # Latest stable
      fail-fast: false

    services:
      db:
        image: ${{ matrix.db.ver == 'mysql' && format('mysql:{0}', matrix.db.release) || format('mariadb:{0}', matrix.db.release) }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: abantecart_test_build
          MYSQL_USER: abantecart
          MYSQL_PASSWORD: cartsarecool

          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: abantecart_test_build
          MARIADB_USER: abantecart
          MARIADB_PASSWORD: cartsarecool
        ports:
          - 3306:3306
        options: >-
          --health-cmd="sh -c 'if command -v mariadb-admin >/dev/null 2>&1; then mariadb-admin ping -h 127.0.0.1 -uroot -proot --silent; else mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; fi'"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=30
          --health-start-period=20s

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, gd, soap, zip, iconv, pdo_mysql
          tools: phpunit:11.5.15

      - name: Install mysql client
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client

      - name: Wait for ${{ matrix.db.ver }} to be ready
        run: |
          to=60
          until mysqladmin ping -h 127.0.0.1 -u abantecart -pcartsarecool --silent || [ $to -eq 0 ]; do
            sleep 1
            echo "not ready yet - remaining $to"
            to=$((to - 1))
          done
          if [ $to -eq 0 ]; then
            echo "DB is not ready" >&2
            docker ps -a
            docker logs "${{ job.services.db.id }}" || true
            exit 1
          fi
          echo "ready"

      - name: Initialize ${{ matrix.db.ver }} Database
        id: db-init
        run: |
          php ./public_html/install/cli_install.php install \
            --db_host=127.0.0.1 \
            --db_user=abantecart \
            --db_password=cartsarecool \
            --db_name=abantecart_test_build \
            --db_driver=amysqli \
            --db_prefix=abc_ \
            --admin_path=admin \
            --username=admin \
            --password=admin \
            --email=dsuprunenko@abantecart.com \
            --http_server=https://abantecart.nowhere/public_html \
            --with-sample-data=public_html/install/abantecart_sample_data.sql \
            --template=novator

      - name: Run phpunit for ${{ matrix.db.ver }}
        run: phpunit -c tests/phpunit/phpunit_mysql.xml
